// packages/example/src/components/CtaSection.tsx
import type { CtaSectionProps } from "../cms/components";

export default function CtaSection({ title, subtitle, decorativeImage }: CtaSectionProps) {
  return (
    <section className="cta">
      {decorativeImage && <img src={decorativeImage} alt="" className="cta-decor" />}
      <h2>{title}</h2>
      {subtitle && <p>{subtitle}</p>}
    </section>
  );
}

// packages/example-vue/src/components/CtaSection.vue
<script setup lang="ts">
import type { CtaSectionProps } from "../cms/components";

defineProps<CtaSectionProps>();
</script>

<template>
  <section class="cta">
    <img v-if="decorativeImage" :src="decorativeImage" alt="" class="cta-decor" />
    <h2>{{ title }}</h2>
    <p v-if="subtitle">{{ subtitle }}</p>
  </section>
</template>
