// packages/example/src/components/PageHero.tsx
import type { PageHeroProps } from "../cms/components";

export default function PageHero({ title, backgroundImage, ctaText, ctaTo }: PageHeroProps) {
  return (
    <section
      className="hero"
      style={{ backgroundImage: backgroundImage ? `url(${backgroundImage})` : undefined }}
    >
      <div className="hero-content">
        <h1>{title}</h1>
        {ctaText && <a href={ctaTo} className="cta-button">{ctaText}</a>}
      </div>
    </section>
  );
}

// packages/example-vue/src/components/PageHero.vue
<script setup lang="ts">
import type { PageHeroProps } from "../cms/components";

defineProps<PageHeroProps>();
</script>

<template>
  <section
    class="hero"
    :style="{ backgroundImage: backgroundImage ? `url(${backgroundImage})` : undefined }"
  >
    <div class="hero-content">
      <h1>{{ title }}</h1>
      <a v-if="ctaText" :href="ctaTo" class="cta-button">{{ ctaText }}</a>
    </div>
  </section>
</template>
