// packages/example-vue/src/components/SplitSection.vue
<script setup lang="ts">
import type { SplitSectionProps } from "../cms/components";

defineProps<SplitSectionProps>();
</script>

<template>
  <section :class="['split', `split--${imagePosition}`]">
    <img :src="imageSrc" :alt="imageAlt" class="split-image" />
    <div class="split-body">
      <h2>{{ title }}</h2>
      <p>{{ text }}</p>
    </div>
  </section>
</template>

// packages/example/src/components/SplitSection.tsx
import type { SplitSectionProps } from "../cms/components";

export default function SplitSection({ imagePosition, imageSrc, imageAlt, title, text }: SplitSectionProps) {
  return (
    <section className={`split split--${imagePosition}`}>
      <img src={imageSrc} alt={imageAlt} className="split-image" />
      <div className="split-body">
        <h2>{title}</h2>
        <p>{text}</p>
      </div>
    </section>
  );
}
